### ISSUE TITLE
✅ [CHORE] Git Issue/Pr Template 만들기

### ISSUE THREAD

**Issue by hwangJi-dev** [TeamNado-Sunbae/NadoSunbae-iOS#1]
## 🙋🏻‍♀️ Feature Issue
Git Issue/Pr Template 만들기

## 🙋🏻‍♀️ 작업 브랜치
- main

## 📝 To-do
- [x] 기능 이슈 템플릿 만들기
- [x] 버그 이슈 템플릿 만들기
- [x] PR 템플릿 만들기
