### ISSUE TITLE
✨ [FEAT] 후기 메인 뷰 Empty View 구성 및 자잘한 UI 수정

### ISSUE THREAD

**Issue by jane1choi** [TeamNado-Sunbae/NadoSunbae-iOS#119]
## 🙋🏻 Feature Issue
- 후기 메인 뷰 Empty View 구성 및 자잘한 UI 수정

## 🙋🏻 작업 브랜치
- feature/#119-UI-Review-EmptyView

## 📝 To-do
- [x] Empty View 구성
- [x] 데이터가 없는 부분 후기 메인 뷰에 Empty View 보여주기
- [x] indicator 추가
- [x] 바텀시트 선택 완료 버튼 틴트컬러 변경
- [x] 텍스트뷰 indicator 컬러 변경
- [x] 글자 수 분기 처리 코드 수정
