### ISSUE TITLE
✨ [FEAT] 과방 정보글 상세뷰 UI 구현

### ISSUE THREAD

**Issue by hwangJi-dev** [TeamNado-Sunbae/NadoSunbae-iOS#125]
## 🙋🏻 Feature Issue
- 과방 정보글 상세뷰 UI 구현

## 🙋🏻 작업 브랜치
- feature/#125-UI-Classroom-infoDetailView

## 📝 To-do
- [x] 전체 tableView
- [x] 상단 질문글 dynamic height 적용하여 xib 구현
- [x] 하단 댓글 xib구현
- [ ] 최하단 textArea
- [ ] 글쓴이/유저 분리
