### ISSUE TITLE
✨ [FEAT] 1:1 질문 TableView UI 기초 틀 구성하기(애니메이션 제외)

### ISSUE THREAD

**Issue by hwangJi-dev** [TeamNado-Sunbae/NadoSunbae-iOS#15]
## 🙋🏻 Feature Issue
과방탭) 1:1 질문 TableView UI 기초 틀 구성하기(애니메이션 제외)

## 🙋🏻 작업 브랜치
- feature/#15-UI-Classroom-1:1QuestionBasic

## 📝 To-do
- [x] TableViewCell 만들기 (질문자 / 답변자 구분)
- [x] 더미 모델 생성
- [x]  더미모델과 연동하여 질문뷰가 잘 구성되는지 확인
