### ISSUE TITLE
✨ [FEAT] 마이페이지 설정 뷰/플로우 구현

### ISSUE THREAD

**Issue by dev-madilyn** [TeamNado-Sunbae/NadoSunbae-iOS#168]
## 🙋🏻 Feature Issue
* 마이페이지 설정 뷰, 플로우 구현

## 🙋🏻 작업 브랜치
- feature/#168-UI-Mypage-Setting

## 📝 To-do
- [x] 설정 목록 구현
- [x] 설정_앱정보 목록 구현
- [x] 플로우 연결
- [x] 로그아웃/탈퇴 알럿 구현
- [x] 인앱 브라우저 연결 처리
