### ISSUE TITLE
✨ [FEAT] 회원가입 - 약관동의 UI 구성

### ISSUE THREAD

**Issue by dev-madilyn** [TeamNado-Sunbae/NadoSunbae-iOS#17]
## 🙋🏻 Feature Issue
* 회원가입 - 약관동의 UI 구성

## 🙋🏻 작업 브랜치
- feature/#17-UI-SignUp-AgreeTerms

## 📝 To-do
- [x] 전체 UI 구성
- [x] 약관 뷰 구성 및 연결
- [x] 체크박스 버튼
- [x] 상단 Navi view 붙이기
