### ISSUE TITLE
✨ [FEAT] 과방 질문상세, 정보상세 하단 textingArea 재사용 컴포넌트로 분리

### ISSUE THREAD

**Issue by hwangJi-dev** [TeamNado-Sunbae/NadoSunbae-iOS#179]
## 🙋🏻 Feature Issue
- 과방 질문상세, 정보상세 하단 textingArea 재사용 컴포넌트로 분리

## 🙋🏻 작업 브랜치
- feature/#179-UI-Recycle-textingArea

## 📝 To-do
- [ ] 하단 textingArea 재사용 컴포넌트로 분리
- [ ] 과방 질문상세에서 재사용 컴포넌트 적용
- [ ] 과방 정보상세에서 재사용 컴포넌트 적용
