### ISSUE TITLE
✨ [FEAT] 과방 정보글 UI 하단 텍스팅 영역, 댓글 기능 구현

### ISSUE THREAD

**Issue by hwangJi-dev** [TeamNado-Sunbae/NadoSunbae-iOS#182]
## 🙋🏻 Feature Issue
- 과방 정보글 UI 하단 텍스팅 영역, 댓글 기능 구현

## 🙋🏻 작업 브랜치
- feature/#182-UI-Classroom-Info-Comment

## 📝 To-do
- [x] 과방 정보글 UI 하단 텍스팅 영역 구현하기
- [x] sendBtn 클릭시 댓글 추가하는 API 연결하기
- [x] 댓글 추가되면 infoDetailTV reaload
