### ISSUE TITLE
✨ [FEAT] 회원가입 - 전공정보 UI 구성

### ISSUE THREAD

**Issue by dev-madilyn** [TeamNado-Sunbae/NadoSunbae-iOS#19]
## 🙋🏻 Feature Issue
* 회원가입 - 전공정보 뷰의 UI를 구성

## 🙋🏻 작업 브랜치
- feature/#19-UI-SignUp-MajorInfo

## 📝 To-do
- [x] 상단 Nav 영역 UI 구성
- [x] 전공정보 UI 구성
- [x] action sheet로 학교 선택
- [x] custom bottom sheet 사용해서 전공 선택
- [x] 이전 화면과 연결
