### ISSUE TITLE
✅ [CHORE] 프로젝트 초기 설정

### ISSUE THREAD

**Issue by hwangJi-dev** [TeamNado-Sunbae/NadoSunbae-iOS#2]
## 🙋🏻 Feature Issue
프로젝트 초기 설정하기 - 폴더링, 탭바, 컬러셋, 폰트, Extension, pod 설치

## 🙋🏻 작업 브랜치
- main

## 📝 To-do
- [x] 프로젝트 생성 후 폴더링
- [x] 컬러셋 생성
- [x] 커스텀 폰트 추가
- [x] 자주 쓰는 Util Extension 파일 추가
- [x] 라이브러리 pod 파일 설치
- [x] 탭바 생성 및 scene 연결
