### ISSUE TITLE
✨ [FEAT] 회원가입 - 기본정보 UI 구성

### ISSUE THREAD

**Issue by dev-madilyn** [TeamNado-Sunbae/NadoSunbae-iOS#21]
## 🙋🏻 Feature Issue
* 회원가입 - 기본정보 UI 구성

## 🙋🏻 작업 브랜치
- feature/#21-UI-SignUp-UserInfo

## 📝 To-do
- [x] 기본정보 UI 구성
- [x] 이메일, 닉네임 확인 버튼 기능
- [x] textfield clear 버튼
- [x] 비밀번호 동일한지 확인하는 기능(with rx)
- [x] 이전 화면과 연결
