### ISSUE TITLE
🔨 [FIX] 로그인, 회원가입 수정 사항

### ISSUE THREAD

**Issue by dev-madilyn** [TeamNado-Sunbae/NadoSunbae-iOS#22]
## 🐞 수정 이유
* 기획, 디자인 변경
* 개발할 때 놓친 부분..

## 🙋 작업 브랜치
* fix/#22-SignInUp

## 📝 To-do
- [x] 로그인 - 아이디, 비밀번호 TextField Clear btn image 변경 (btnXGray)
- [x] 로그인 - 아이디, 비밀번호 TextField Cleat btn 편집 중/isEmpty==false 일 때만 보이게
- [x] 회원가입 - 약관동의: 이전 버튼 삭제, 디자인 변경
- [x] 회원가입 - 약관동의: 전체 동의 버튼 영역 텍스트필드 전체로 확장
- [x] 회원가입 - 약관동의: 다음 버튼 disable 처리 확실하게
- [x] 회원가입 - 전공정보: 선택 버튼 영역 텍스트필드 전체로 확장
- [x] 회원가입 - 전공정보: 다음 버튼 disable 처리 확실하게
- [x] 회원가입 - 전공정보: 텍스트필드가 공란이 아닐 경우, '선택' 버튼을 '변경' 버튼으로 변경
- [x] 회원가입 상단 progress view 높이.. 비율로 설정
