### ISSUE TITLE
🔨 [FIX] 과방 질문 채팅 스레드뷰 QA 반영

### ISSUE THREAD

**Issue by hwangJi-dev** [TeamNado-Sunbae/NadoSunbae-iOS#258]
## 🐞 버그 설명
[과방] 수정 클릭시 취소/확인 버튼까지 안 보임
- 채팅뷰 하단 텍스트영역 뒤로가기하고 재진입시 위로 올라오는 현상
- 키보드 영역만큼 스크롤이 안되는 현상 (바닥부분) 뷰가 더 늘어나야함. (키보드 올라올 때)
    - 맨 하단 셀 수정누를 때 동일.
   
## 🙋 작업 브랜치
- qa/#258-Classroom-QuestionDetail-Bug

## 📝 To-do
- [x] 채팅뷰 하단 텍스트영역 뒤로가기하고 재진입시 위로 올라오는 현상 해결
- [x] 키보드 영역만큼 스크롤이 안되는 현상 (바닥부분) -> 뷰가 더 늘어나게 수정하기 (키보드 올라올 때)
    - [x] 맨 하단 셀 수정누를 때 동일 현상 해결
