### ISSUE TITLE
🔨 [FIX] 후기 상세 뷰 프로필관련 QA 대응

### ISSUE THREAD

**Issue by jane1choi** [TeamNado-Sunbae/NadoSunbae-iOS#303]
## 🐞 버그 설명
- 후기 상세 뷰 내 프로필 클릭 시 마이페이지로 이동하도록 분기처리
- 후기 상세 뷰 프로필 화살표 버튼 클릭 시에도 화면전환 되도록 수정
- 텍스트 분기처리

## 🙋 작업 브랜치
- fix/#-UI-Review-ReviewDetailProfile

## 📝 To-do
- [ ] 후기 상세 뷰 내 프로필 클릭 시 마이페이지로 이동하도록 분기처리
- [ ] 후기 상세 뷰 프로필 화살표 버튼 클릭 시에도 화면전환 되도록 수정
- [ ] 선배에게 질문~ 텍스트 내가 쓴 글에는 안뜨도록
