### ISSUE TITLE
✨ [FEAT] 과방탭 유저의 프로필 이미지, 닉네임을 클릭했을 때 유저의 마이페이지로 이동하는 기능 구현

### ISSUE THREAD

**Issue by hwangJi-dev** [TeamNado-Sunbae/NadoSunbae-iOS#305]
## 🙋🏻 Feature Issue
- 유저의 프로필 이미지, 닉네임을 클릭했을 때 유저의 마이페이지로 이동하는 기능 구현

## 🙋🏻 작업 브랜치
- feature/#305-Classroom-GoToMypageWhenClick

## 📝 To-do
- [x] 유저의 프로필 이미지 클릭했을 때 유저의 마이페이지로 이동
- [x] 닉네임을 클릭했을 때 유저의 마이페이지로 이동
- [x] 나의 마이페이지, 선배의 마이페이지 분기처리
