### ISSUE TITLE
🔨 [FIX] 프로필 수정 QA 대응

### ISSUE THREAD

**Issue by dev-madilyn** [TeamNado-Sunbae/NadoSunbae-iOS#308]
## 🐞 버그 설명
스크린 샷, 작동 환경 (OS, device 등)을 적어주세요.
[노션](https://www.notion.so/nadosunbae/8ef8e7ba0f1f410fad74dfc4a9061314)
![스크린샷 2022-03-09 오전 2 07 57](https://user-images.githubusercontent.com/43312096/157288946-da8d4392-32b2-4d3d-8d83-6a07a302fbbc.png)

## 🙋 작업 브랜치
fix/#308-QA-ProfileSetting

## 📝 To-do
- [x] 닉네임 텍스트필드 검정색으로 바꾸기(통신 완료 시 플레이스홀더X 걍텍스트)
- [x] 닉네임 변경 버튼 누를 때 키보드 내려가게
- [x] 닉네임 변경 버튼 -> 확인으로 바꾸기
- [x] 제2전공 진입시기 선택 버튼 상태에 따라 텍스트 바꾸기
