### ISSUE TITLE
🔨 [FIX] 회원가입 QA 대응

### ISSUE THREAD

**Issue by dev-madilyn** [TeamNado-Sunbae/NadoSunbae-iOS#328]
## 🐞 버그 설명
스크린 샷, 작동 환경 (OS, device 등)을 적어주세요.
<img width="319" alt="스크린샷 2022-03-09 오후 8 29 45" src="https://user-images.githubusercontent.com/43312096/157433313-477f7c21-72ab-4217-a0f1-4bc7e59db5a1.png">

<img width="727" alt="스크린샷 2022-03-09 오후 8 29 56" src="https://user-images.githubusercontent.com/43312096/157433338-08f83d28-ced5-450f-a1f7-43b0c92f37fd.png">
<img width="721" alt="스크린샷 2022-03-09 오후 8 31 35" src="https://user-images.githubusercontent.com/43312096/157433571-bf90c886-ce6b-461b-adf1-239009c5dbb9.png">
<img width="752" alt="스크린샷 2022-03-09 오후 8 32 32" src="https://user-images.githubusercontent.com/43312096/157433698-1b38580a-9f50-437a-91ba-537c765c5e9e.png">

## 🙋 작업 브랜치
fix/#328-QA-SignUp

## 📝 To-do
- [x] 유저정보 > 이메일 입력 placeholder가 아닌 text에 "@korea.ac.kr" 넣어두기
- [x] 이메일 확인 시 "@korea.ac.kr"가 아니면 버튼 비활성화되게하기
- [x] 회원가입 유저정보 입력후 무한로딩 테스트및수정
- [x] 전공 진입시기 for문 싹다수정(최신순으로, 22-2제외)
- [x] 회원가입 유저정보 입력 화면에서 키보드 올라올 때 높이 처리(추천단어 있을때 등등..)
