### ISSUE TITLE
✨ [FEAT] 마이페이지 - 개인페이지 UI 구성

### ISSUE THREAD

**Issue by dev-madilyn** [TeamNado-Sunbae/NadoSunbae-iOS#35]
## 🙋🏻 Feature Issue
* 마이페이지 - 메인 UI 구성

## 🙋🏻 작업 브랜치
- feature/#35-UI-MyPage-User

## 📝 To-do
- [x] Nav 영역 View UI 구현
- [x] userStateBar 적용 - 상태별 레이아웃 변경 처리
- [x] 유저 정보 영역 UI 구현
- [x] 1:1 질문 UI 구현
