### ISSUE TITLE
✨ [FEAT] 채팅 UI 하단 텍스트 입력 Area 세부 기능 구현 및 애니메이션 추가

### ISSUE THREAD

**Issue by hwangJi-dev** [TeamNado-Sunbae/NadoSunbae-iOS#36]
## 🙋🏻 Feature Issue
채팅 UI 하단 텍스트 입력 Area 세부 기능 구현 및 애니메이션 추가

## 🙋🏻 작업 브랜치
- feature/#36-UI-Classroom-TextAreaDetail

## 📝 To-do
- [x] 텍스트뷰 left padding 추가
- [x] 텍스트뷰 4줄 이상 입력시 내부 스크롤 추가
- [x] 텍스트뷰 placeholder 세부 설정
- [x] 텍스트뷰 텍스트 vertical center positioning
- [x] send Animation + reloadTV
