### ISSUE TITLE
✨ [FEAT] 채팅 UI 키보드 인터랙션 기능 구현

### ISSUE THREAD

**Issue by hwangJi-dev** [TeamNado-Sunbae/NadoSunbae-iOS#40]
## 🙋🏻 Feature Issue
- 채팅 UI 키보드 인터랙션 기능 구현

## 🙋🏻 작업 브랜치
- feature/#40-UI-Classroom-ChattingKeyboardAction

## 📝 To-do
- [x] userType별 분기처리 -> 작성자/답변자/타인
- [x] send 액션시 textView clear
- [x] 과방탭 질문하기뷰 텍스트 에어리어 텍스팅시 키보드 인터랙션 -> 텍스트 에어리어 keyboard 높이만큼 위로 올라가게
- [x] TV 키보드 높이만큼 올라가기
- [x] NavigationBar 완성 + 기능 붙이기
