### ISSUE TITLE
✨ [FEAT] 회원가입 UI + API 수정

### ISSUE THREAD

**Issue by dev-jungbin** [TeamNado-Sunbae/NadoSunbae-iOS#459]
## 🙋🏻 Feature Issue
* 회원가입 부분 UI와 API를 수정합니다.

## 🙋🏻 작업 브랜치
- feature/#459-SIgnUp-UI-API

## 📝 To-do
- [x] 학교명 선택창에 default값 "선택하기"로 변경
- [x] 학교명 선택 바텀시트에 서울여대, 중앙대 추가
- [x] 특정학교 선택 시 전공 리스트 업뎃
- [x] 바텀시트 변경(은주 pr 참고)
- [x] 학교명 선택 전 다른 요소들 선택 비활성화
- [x] 고대, 중앙대, 설여 univ id 변경
- [x] 바텀시트 선택 후 처리
- [x] 전공정보 기입 뷰 SE 레이아웃 수정
- [x] 기본정보 학교 이메일 자동으로 써 있는 거 학교 이메일로 변경
- [x] API 모델 및 path 점검
- [x] API 리팩토링(judge 삭제)
- [x] 로그인 textfield placeholder 수정
