### ISSUE TITLE
✨ [FEAT] 알림 탭 API 수정

### ISSUE THREAD

**Issue by dev-jungbin** [TeamNado-Sunbae/NadoSunbae-iOS#479]
## 🙋🏻 Feature Issue
* 알림 탭 관련 APi를 수정합니다.

## 🙋🏻 작업 브랜치
- network/#479-Notification-API

## 📝 To-do
- [x] NotiType 수정, getNotiType 수정
- [x] 알림 리스트 조회 API 수정
- [x] 알림 읽음 처리 API 점검
- [x] 알림 삭제 API 점검
