### ISSUE TITLE
✨ [FEAT] 홈 탭 화면전환 연결 및 후기 상세 뷰 UI 수정사항 반영

### ISSUE THREAD

**Issue by jane1choi** [TeamNado-Sunbae/NadoSunbae-iOS#489]
## 🙋🏻 Feature Issue
홈 탭 화면전환 연결 및 후기 상세 뷰 UI 수정사항을 반영합니다.

## 🙋🏻 작업 브랜치
- feature/#489-UI-Home-PresentDetail

## 📝 To-do
- [x] 랭킹 뷰 화면전환 연결
- [x] 최근 후기 뷰 화면전환 연결
- [x] 후기 상세 뷰 UI 수정사항 반영
- [x] 후기 상세 조회 API 수정사항 반영
