### ISSUE TITLE
✨ [FEAT] 마이페이지 - 메인 UI

### ISSUE THREAD

**Issue by dev-madilyn** [TeamNado-Sunbae/NadoSunbae-iOS#49]
## 🙋🏻 Feature Issue
* 마이페이지 - 메인 UI를 작업합니다! '본인' 페이지입니다!!

## 🙋🏻 작업 브랜치
- feature/#49-UI-Mypage-User-Main

## 📝 To-do
- [x] UI 구성
- [x] 상태별 분기 처리
- [x] 버튼 액션들 빼 놓기~..
- [x] 기능별 우선순위 구분해서 dummy 넣을지, 구현할지 주석 문서화 달아 놓기
