### ISSUE TITLE
🔨 [FIX] 마이페이지 QA 수정

### ISSUE THREAD

**Issue by dev-jungbin** [TeamNado-Sunbae/NadoSunbae-iOS#494]
## 🐞 버그 설명
<img width="411" alt="image" src="https://user-images.githubusercontent.com/43312096/194197368-1263ffff-f436-4435-8ce3-7bd685fa93a3.png">
작성중..

## 🙋 작업 브랜치
* fix/#494-Mypage-QA

## 📝 To-do
- [x] 마이페이지 SegmentedControl 사용된 부분 레이아웃 수정
- [x] 내가 쓴 답글(뿐만ㅇ 아니라 다른 뷰들 ) emptyView 처리(내가쓴 답글_1:1질문 노출 안됨 QA 관련)
- [x] 좋아요 목록 / 내가 쓴 글 탭_커뮤니티 글 상세 페이지로 연동 불가
