### ISSUE TITLE
✨ [FEAT] 후기 탭 상단 바 및 학과 선택 뷰 구현

### ISSUE THREAD

**Issue by jane1choi** [TeamNado-Sunbae/NadoSunbae-iOS#5]
## 🙋🏻 Feature Issue
후기 탭 상단 바와 버튼 클릭 시 나타나는 학과 선택 `halfModalView`를 재사용 가능하도록 구현합니다.

## 🙋🏻 작업 브랜치
- feature/#5-UI-review-halfmodal

## 📝 To-do
- [x] 상단 바 UI 구현
- [ ] 학과 선택 뷰 구현
- [ ] 학과 선택 뷰 버튼 CustomClass 적용
