### ISSUE TITLE
🔨 [FIX] 회원가입 QA 수정

### ISSUE THREAD

**Issue by dev-jungbin** [TeamNado-Sunbae/NadoSunbae-iOS#508]
## 🐞 버그 설명
* 기본정보선택_학교 이메일 중복 확인 버튼 클릭 시 “사용 가능한 이메일 입니다.” 멘트 없음 (공유 필요)
* 완료 조건 충족 되어도 버튼 미활성화
* 전공정보선택_학과검색  선택시 해당 내용 반영 안됨

## 🙋 작업 브랜치
* fix/#508-SignUp-QA
* fix/#508-SignUp-UserInfo-QA

## 📝 To-do
- [x] 전공정보선택_학과검색  선택시 해당 내용 반영 안됨
- [x] 기본정보선택_학교 이메일 중복 확인 버튼 클릭 시 “사용 가능한 이메일 입니다.” 멘트 없음
- [x] 완료 조건 충족 되어도 버튼 미활성화
