### ISSUE TITLE
✨ [FEAT] NadoSunbae Segment Custom View 재사용 컴포넌트 생성

### ISSUE THREAD

**Issue by hwangJi-dev** [TeamNado-Sunbae/NadoSunbae-iOS#52]
## 🙋🏻 Feature Issue
- NadoSunbae Segment Custom View 재사용 컴포넌트 생성

## 🙋🏻 작업 브랜치
- feature/#52-UI-Component-NadoSegmentView

## 📝 To-do
- [x] 세그먼트 뷰가 될 (질문,정보 버튼) 재사용 뷰 생성
- [x] 컨테이너뷰 2개 틀이 될 -> 재사용 ContainerView 생성 
- [x] 컴포넌트 불러와 재사용 잘 되는지 테스트
