### ISSUE TITLE
✨ [FEAT] 커뮤니티 학과 필터기능을 구현합니다.

### ISSUE THREAD

**Issue by hwangJi-dev** [TeamNado-Sunbae/NadoSunbae-iOS#541]
## 🙋🏻 Feature Issue
- 커뮤니티 학과 필터기능을 구현합니다.

## 🙋🏻 작업 브랜치
- feature/#541-community-majorFilter

## 📝 To-do
- [x] 학과 필터버튼 누르면 바텀시트 띄우기
- [x] 바텀시트 - 커뮤니티뷰간 데이터 전달
- [x] 커뮤니티 필터일때 -> 바텀시트 재클릭시 선택해제 되는 기능 구현
- [x] 전체글 / 학과무관 구분
