### ISSUE TITLE
✅ [CHORE] BaseQuestionTVC관련 중복 파일을 제거하고 TVC를 통일합니다.

### ISSUE THREAD

**Issue by hwangJi-dev** [TeamNado-Sunbae/NadoSunbae-iOS#542]
## 🙋🏻 Feature Issue
- QuestionTVC관련 중복 파일을 제거하고 TVC를 통일합니다.

## 🙋🏻 작업 브랜치
- chore/#542-baseQuestionTVC-removeDuplicate

## 📝 To-do
- [x] BaseQuestionTVC관련 중복 파일 제거 (EntireQuestionTVC, QuestionTVC 등)
- [x] BaseQuestionTVC로 코드 통일 
- [x] EntireQuestionTVC로 사용하던 코드들 TableView에 top inset 추가하기
