### ISSUE TITLE
✨ [FEAT] 후기 상세 뷰 UI 구성

### ISSUE THREAD

**Issue by jane1choi** [TeamNado-Sunbae/NadoSunbae-iOS#57]
## 🙋🏻 Feature Issue
- 후기 상세 뷰의 UI를 구성합니다.

## 🙋🏻 작업 브랜치
- feature/#57 -UI-Review-DetailView

## 📝 To-do
- [x] 배경 이미지 삽입
- [x] 전체 `TableView` 구성
- [x] 수정, 삭제 `ActionSheet` 삽입
- [ ] 글 길이에 다른 동적 높이 구현
