### ISSUE TITLE
✨ [FEAT] 알림 UI 구성

### ISSUE THREAD

**Issue by dev-madilyn** [TeamNado-Sunbae/NadoSunbae-iOS#59]
## 🙋🏻 Feature Issue
* 알림 탭의 UI를 개발합니다.

## 🙋🏻 작업 브랜치
- feature/#59-Notification-UI

## 📝 To-do
- [x] nav View
- [x] table view cell
- [x] dummy data model
- [x] table view action(삭제, 읽음 처리)
- [x] 알림 case별 텍스트 처리
- [x] 시간 string 처리 -> 서버 어케 드러오는지 보고~
