### ISSUE TITLE
✨ [FEAT] 바텀시트 학과 즐겨찾기 기능 구현

### ISSUE THREAD

**Issue by jane1choi** [TeamNado-Sunbae/NadoSunbae-iOS#614]
## 🙋🏻 Feature Issue
바텀시트 내의 학과 즐겨찾기 기능을 구현합니다.

## 🙋🏻 작업 브랜치
- feature/#614-BottomSheet-StarMajor

## 📝 To-do
- [x] 즐겨찾기 API 연결
- [x] 즐겨찾기 정보 저장
- [x] 즐겨찾기한 학과가 위에 뜨도록 구현
