### ISSUE TITLE
✅ [CHORE] 후기 작성 뷰 Asset 변경 및 기능 추가

### ISSUE THREAD

**Issue by jane1choi** [TeamNado-Sunbae/NadoSunbae-iOS#66]
## 🙋🏻 Feature Issue
- 디자인 수정사항에 따른 후기 작성 뷰의 배경 이미지 에셋 변경
- 완료 버튼 시 나타나는 커스텀 팝업 창 추가

## 🙋🏻 작업 브랜치
- chore/#66-UI-Review-WriteView

## 📝 To-do
- [x] 이미지 에셋 추가
- [x] 배경 이미지 선택 시 체크 버튼 뜨도록
- [ ] 완료 버튼 클릭 시 나타나는 커스텀 팝업 창 구현
