### ISSUE TITLE
✨ [FEAT] 1순위 GA 이벤트 수집기능 추가

### ISSUE THREAD

**Issue by hwangJi-dev** [TeamNado-Sunbae/NadoSunbae-iOS#680]
## 🙋🏻 Feature Issue
- 1순위 GA 이벤트 수집기능 추가

## 🙋🏻 작업 브랜치
- feature/#680-classroom-ga

## 📝 To-do
- [x] 과방 1:1 질문 관련 GA 이벤트 수집기능 추가
- [x] 질문가능 선배 관련 GA 이벤트 수집기능 추가
- [x] signup_process
- [x] write_requset_alert
- [x] review_process
- [x] review_read
- [x] question_read_1on1
- [x] senior_click
- [x] question_answered_1on1
- [x] mention_function
- [x] review_write
- [x] question_write_1on1
