### ISSUE TITLE
✅ [CHORE] 후기 메인 뷰 UI 수정   

### ISSUE THREAD

**Issue by jane1choi** [TeamNado-Sunbae/NadoSunbae-iOS#83]
## 🙋🏻 Feature Issue
- 후기 메인 뷰 UI를 수정합니다.

## 🙋🏻 작업 브랜치
- chore/#83-UI-Review-MainView

## 📝 To-do
- [x] 최신순 필터 이미지 변경
- [x] 태그 부분 `StackView` -> `CollectionView` 변경
- [x] `HalfModal` 버튼 선택 액션 추가
